version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - /app/node_modules
      - .:/app
