services:
  client:
    build: .
    image: kamalhossain/react-counter-app-client
    restart: always
    ports:
      - "80:80"
    volumes:
      - /usr/src/app/node_modules
      - ./services/client:/usr/src/app
